In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import numpy

In [2]:
import numpy as np

In [3]:
arr = np.array(42)

print(arr)

42


In [4]:
arr_1 = np.array([1, 2, 3])

In [5]:
arr_2 = np.array([[1], [2], [3]])

In [6]:
print(arr_2)

[[1]
 [2]
 [3]]


In [7]:
arr_3 = np.array([[1, 1], [2, 2], [3, 3]])

In [8]:
arr_3.shape

(3, 2)

In [5]:
arr_4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr_4)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [6]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
arr_5 = np.array([1, 2, 3, 4], ndmin=5)

print(arr_5)
print('number of dimensions :', arr_5.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [9]:
arr_3[1, 0]

2

In [10]:
arr_3[0:2, 0]

array([1, 2])

In [11]:
arr_3[1:3, 0:2]

array([[2, 2],
       [3, 3]])

In [12]:
arr_3[:, 1]

array([1, 2, 3])

In [13]:
arr_3[1:, 0]

array([2, 3])

In [14]:
np.zeros((2, 4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((1, 5))

array([[0., 0., 0., 0., 0.]])

In [17]:
np.zeros((5, 1))

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [18]:
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

 با استفاده از دستور ones، یک بردار ستونی یک به طول 5 بسازید.

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.eye(4, 6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [22]:
np.full((5, 3), 2)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [23]:
np.full((7, 1), 4)

array([[4],
       [4],
       [4],
       [4],
       [4],
       [4],
       [4]])

 یک بردار به طول 15 بسازید که تمام عناصر آن عدد 7 باشند.

In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
